image: Visual Studio 2017

clone_folder: "C:\\projects\\safe_mobile"

environment:
  ANDROID_HOME: "C:\\android-sdk-windows"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  CAKE_SETTINGS_SKIPVERIFICATION: "true"

cache:
  - '%ANDROID_HOME%'
  - '%temp%\nativeauthlibs'
  - '%USERPROFILE%\.nuget\packages'
  - SafeAuthenticator\CakeScripts\tools -> SafeAuthenticator\CakeScripts\build.cake, SafeAuthenticator\CakeScripts\build.ps1, SafeAuthenticator\CakeScripts\build.sh

install:
  - cd \
  - if not exist android-sdk-windows appveyor DownloadFile http://dl.google.com/android/android-sdk_r24.4.1-windows.zip
  - if not exist android-sdk-windows 7z x android-sdk_r24.4.1-windows.zip > nul 
  - cd C:\projects\safe_mobile
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-21.0.0
  #- echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-26.0.2
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-21
  #- echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-26
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-google-m2repository
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-android-m2repository
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t sys-img-armeabi-v7a-android-21
  #- echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t sys-img-x86_64-android-26   

before_build:
  - echo no | "%ANDROID_HOME%\tools\android.bat" create avd --force -n SafeEmulator -t android-21 --abi armeabi-v7a
  #- echo no | "%ANDROID_HOME%\tools\android.bat" create avd --force -n SafeEmulator -t android-26 --abi default/x86_64
  - ps: Start-Process "C:\android-sdk-windows\tools\emulator.exe" "-avd SafeEmulator -no-audio -no-window" 
  # - ps: Start-sleep -s 120
  # - echo dummy | "%ANDROID_HOME%\platform-tools\adb.exe" shell input keyevent 82 

build_script:
  - ps: $env:Path += ";C:\android-sdk-windows\platform-tools";
  - ps: $env:Path += ";C:\android-sdk-windows\tools";
  - ps: $env:Path += ";C:\android-sdk-windows\tools\bin";
  - ps: cd SafeAuthenticator/CakeScripts
  - powershell .\build.ps1 -Target Default -Verbosity normal
  - ' "%ANDROID_HOME%\platform-tools\adb.exe" emu kill -9 '   

test: off
