cache:
  - '%temp%\nativeauthlibs'
  - packages -> **\**\packages.config
  - '%USERPROFILE%\.nuget\packages'
  - SafeAuthenticator\tools -> SafeAuthenticator\CakeScripts\build.cake, SafeAuthenticator\CakeScripts\build.ps1, SafeAuthenticator\CakeScripts\build.sh

image: Visual Studio 2017

build_script:
  - ps: cd SafeAuthenticator/CakeScripts/
  - ps: ./build.ps1